// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    use: function() {
      String.prototype.splitNum = function(separator) {
        var arr, c, pre, s, str, _i, _j, _len, _len1;
        arr = [];
        str = '';
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          c = this[_i];
          str += c;
        }
        pre = str.split(separator);
        for (_j = 0, _len1 = pre.length; _j < _len1; _j++) {
          s = pre[_j];
          arr.push(Number(s));
        }
        return arr;
      };
      Number.prototype.toHex = function(padding) {
        var hexNum;
        hexNum = this.toString(16);
        if (hexNum.length < padding) {
          hexNum = Array(padding - hexNum.length + 1).join('0') + hexNum;
        }
        return '0x' + hexNum;
      };
      return Array.prototype.addBytes = function(arr) {
        var num, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = arr.length; _i < _len; _i++) {
          num = arr[_i];
          _results.push(this.push(num));
        }
        return _results;
      };
    }
  };

}).call(this);
